
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/QuantumNous/new-api/relay/channel/vertex"


)

var tests = []testing.InternalTest{

	{"TestVertexAnthropicRequestConvertsToGemini", _test.TestVertexAnthropicRequestConvertsToGemini},

	{"TestVertexAnthropicNonstreamResponses", _test.TestVertexAnthropicNonstreamResponses},

	{"TestVertexAnthropicStreamBlocksAndTerminalUsage", _test.TestVertexAnthropicStreamBlocksAndTerminalUsage},

	{"TestVertexAnthropicFailedStreamsNeverStopSuccessfully", _test.TestVertexAnthropicFailedStreamsNeverStopSuccessfully},

	{"TestVertexAnthropicNonstreamErrorsAndOpenAIEntry", _test.TestVertexAnthropicNonstreamErrorsAndOpenAIEntry},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/QuantumNous/new-api"
	testdeps.ImportPath = "github.com/QuantumNous/new-api/relay/channel/vertex"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

