# .github/workflows/test-ci.yml
name: Build for Test Environment

on:
  push:
    branches:
      - prod # 只监听 prod 分支的变更

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Test Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 固定打上 test 标签，供测试服务器拉取
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
