version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
    - web
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
