export const PRICING_PLANS = [
  {
    id: 'free',
    name: '免费版',
    platformFees: '无',
    models: '25+ 免费模型',
    providers: '4 个免费提供商',
    chatApi: true,
    activityLogs: true,
    autoRouting: true,
    budgets: true,
    promptCaching: true,
    provisioning: true,
    adminControls: true,
    dataPolicyRouting: true,
    managedPolicy: true,
    providerDataExplorer: true,
    ssoSaml: false,
    contractualSlas: false,
    paymentOptions: '信用卡、加密货币等',
    tokenPricing: '仅限免费模型',
    support: '社区支持',
    ctaText: '免费开始',
    ctaLink: '/auth/register',
    popular: false,
  },
  {
    id: 'payg',
    name: '按需付费',
    platformFees: '5.5%',
    models: '300+ 模型',
    providers: '60+ 提供商',
    chatApi: true,
    activityLogs: true,
    autoRouting: true,
    budgets: true,
    promptCaching: true,
    provisioning: true,
    adminControls: true,
    dataPolicyRouting: true,
    managedPolicy: true,
    providerDataExplorer: true,
    ssoSaml: false,
    contractualSlas: false,
    paymentOptions: '信用卡、加密货币等',
    tokenPricing: '无最低消费，按模型定价',
    support: '邮件支持',
    ctaText: '购买额度',
    ctaLink: '/console/tokens',
    popular: true,
  },
  {
    id: 'enterprise',
    name: '企业版',
    platformFees: '批量折扣可用',
    platformFeesLink: '/enterprise',
    models: '300+ 模型',
    providers: '60+ 提供商',
    chatApi: true,
    activityLogs: true,
    autoRouting: true,
    budgets: true,
    promptCaching: true,
    provisioning: true,
    adminControls: true,
    dataPolicyRouting: true,
    managedPolicy: true,
    providerDataExplorer: true,
    ssoSaml: true,
    contractualSlas: true,
    paymentOptions: '发票选项',
    tokenPricing: '批量承诺，按模型定价',
    support: '支持 SLA + 共享 Slack 频道',
    ctaText: '联系销售',
    ctaLink: '/enterprise',
    popular: false,
  },
] as const;

export const FAQ_CATEGORIES = [
  {
    id: 'billing',
    title: '计费与定价',
    questions: [
      {
        id: 'tokens-billed',
        question: '如何计费 token？',
        answer: 'Token 根据每个模型的实际使用量计费。输入 token 和输出 token 可能根据模型提供商有不同的费率。',
      },
      {
        id: 'markup',
        question: '会对提供商定价加价吗？',
        answer: '按需付费计划收取 5.5% 的平台费用。企业计划提供批量折扣和自定义定价。',
      },
      {
        id: 'billing-structure',
        question: 'BYOK、按需付费和企业版的计费结构是怎样的？',
        answer: 'BYOK（自带密钥）允许使用自己的 API 密钥。按需付费按使用量收取 5.5% 费用。企业版提供自定义合同和批量折扣。',
      },
      {
        id: 'failed-attempts',
        question: '失败或回退请求会计费吗？',
        answer: '失败的请求不计费。成功的回退请求根据最终提供服务的模型计费。',
      },
      {
        id: 'volume-discounts',
        question: '提供批量折扣或年度计划吗？',
        answer: '是的，企业计划提供批量折扣和年度承诺。联系销售获取自定义定价。',
      },
      {
        id: 'streaming',
        question: '流式响应的计费方式不同吗？',
        answer: '不，流式响应与非流式响应计费方式相同。Token 在生成时计数。',
      },
      {
        id: 'payment-methods',
        question: '接受哪些支付方式？',
        answer: '我们接受信用卡、加密货币和各种支付处理器。企业客户可以使用发票。',
      },
      {
        id: 'taxes',
        question: '价格是否包含税费（VAT/GST）？',
        answer: '价格不包含税费。VAT/GST 将根据您的位置添加给适用客户。',
      },
      {
        id: 'minimum-spend',
        question: '按需付费有最低消费或锁定期吗？',
        answer: '按需付费无需最低消费或锁定期。按实际使用付费。',
      },
    ],
  },
  {
    id: 'usage',
    title: '使用与速率限制',
    questions: [
      {
        id: 'rate-limits',
        question: '会执行速率限制吗？',
        answer: '是的，我们有速率限制以确保公平使用。企业计划提供更高的限制和自定义速率限制。',
      },
      {
        id: 'environments',
        question: '可以分离环境（开发/测试/生产）吗？',
        answer: '是的，您可以为不同环境创建单独的 API 密钥并独立跟踪使用情况。',
      },
      {
        id: 'platform-limits',
        question: '会执行平台速率限制吗？',
        answer: '平台速率限制适用于确保稳定性。企业计划可以协商自定义限制。',
      },
    ],
  },
  {
    id: 'routing',
    title: '路由与延迟',
    questions: [
      {
        id: 'regions',
        question: '可以确保在特定区域发送 API 请求吗？',
        answer: '是的，您可以指定首选区域。我们的路由将优先选择这些区域中的提供商（如果可用）。',
      },
      {
        id: 'routing-latency',
        question: '路由会影响延迟吗？',
        answer: '路由增加的延迟最小（通常 <50ms）。我们的智能路由同时优化成本和速度。',
      },
      {
        id: 'deprecated-models',
        question: '如果模型被弃用或定价更改会怎样？',
        answer: '我们会通知用户更改并提供迁移路径。自动路由可以自动切换到替代模型。',
      },
      {
        id: 'pin-versions',
        question: '可以固定特定模型版本吗？',
        answer: '是的，您可以固定到特定模型版本以确保一致性，或使用自动路由获取最新版本。',
      },
    ],
  },
  {
    id: 'privacy',
    title: '隐私与安全',
    questions: [
      {
        id: 'training-data',
        question: '会在客户数据上训练吗？',
        answer: '不，我们不会在客户数据上训练。您的提示词和响应不会用于训练。',
      },
      {
        id: 'sso',
        question: '支持 SSO 吗？',
        answer: '是的，企业计划支持 SSO/SAML 用于团队管理和安全。',
      },
    ],
  },
  {
    id: 'models',
    title: '模型与功能',
    questions: [
      {
        id: 'migration',
        question: '如何从 OpenAI/Anthropic 迁移？',
        answer: '只需将基础 URL 更改为我们的端点并使用您的 API 密钥。我们的 API 完全兼容 OpenAI 和 Anthropic。',
      },
      {
        id: 'function-calling',
        question: '支持函数调用/工具吗？',
        answer: '是的，我们支持函数调用、工具以及底层模型中可用的其他高级功能。',
      },
    ],
  },
  {
    id: 'reliability',
    title: '可靠性与正常运行时间',
    questions: [
      {
        id: 'provider-down',
        question: '如果提供商宕机或模型出错会怎样？',
        answer: '我们的自动路由会自动回退到替代提供商或模型，确保您的请求成功。',
      },
      {
        id: 'uptime-check',
        question: '在哪里可以查看正常运行时间和事件？',
        answer: '查看我们的状态页面 status.openrouter.ai 获取实时正常运行时间信息和事件报告。',
      },
    ],
  },
] as const;