import type { HomeMarketListing, HomeTokenRoute } from '@/types/homeShowcase'

export const HOME_LAUNCHED_AT = '2026-03-15T00:00:00+08:00'
export const HOME_REQUEST_SEED = 32_132

export const HOME_MARKET_LISTINGS: HomeMarketListing[] = [
  {
    id: 'aurora-gpt',
    provider: 'Aurora Relay',
    model: 'gpt-5-mini',
    region: 'Tokyo',
    price: 0.82,
    availability: 99.97,
    qualityScore: 96,
    status: 'available',
    source: 'market',
  },
  {
    id: 'northstar-claude',
    provider: 'Northstar API',
    model: 'claude-sonnet-4',
    region: 'Frankfurt',
    price: 0.91,
    availability: 99.92,
    qualityScore: 94,
    status: 'available',
    source: 'market',
  },
  {
    id: 'mosaic-gemini',
    provider: 'Mosaic Compute',
    model: 'gemini-2.5-pro',
    region: 'Singapore',
    price: 0.76,
    availability: 99.88,
    qualityScore: 92,
    status: 'available',
    source: 'market',
  },
]

export const HOME_SELL_LISTINGS: HomeMarketListing[] = [
  {
    id: 'personal-vision',
    provider: 'My Vision Gateway',
    model: 'gpt-image-2',
    region: 'Hong Kong',
    price: 1.08,
    availability: 99.81,
    qualityScore: 91,
    status: 'draft',
    source: 'market',
  },
]

export const HOME_TOKEN_ROUTES: HomeTokenRoute[] = [
  {
    id: 'production-key',
    name: 'production-key',
    maskedKey: 'sk-ren2••••••••7A91',
    mode: 'manual',
    loadBalance: false,
    channels: [
      {
        id: 'prod-official-primary',
        listingId: null,
        name: '',
        nameKey: 'showcase.routing.channels.productionPrimary',
        provider: 'Ren2 Official',
        model: 'gpt-5-mini',
        source: 'official',
        weight: 55,
        enabled: true,
        latency: 186,
        qualityScore: 98,
        health: 'degraded',
      },
      {
        id: 'prod-market-backup',
        listingId: 'seed-market-route',
        name: '',
        nameKey: 'showcase.routing.channels.auroraMarket',
        provider: 'Aurora Relay',
        model: 'gpt-5-mini',
        source: 'market',
        weight: 30,
        enabled: true,
        latency: 238,
        qualityScore: 96,
        health: 'online',
      },
      {
        id: 'prod-cold-backup',
        listingId: null,
        name: '',
        nameKey: 'showcase.routing.channels.coldBackup',
        provider: 'Ren2 Official',
        model: 'claude-sonnet-4',
        source: 'official',
        weight: 15,
        enabled: false,
        latency: 312,
        qualityScore: 95,
        health: 'online',
      },
    ],
  },
  {
    id: 'image-worker',
    name: 'image-worker',
    maskedKey: 'sk-ren2••••••••C204',
    mode: 'auto',
    loadBalance: true,
    channels: [
      {
        id: 'image-official',
        listingId: null,
        name: '',
        nameKey: 'showcase.routing.channels.imageOfficial',
        provider: 'Ren2 Official',
        model: 'gpt-image-2',
        source: 'official',
        weight: 65,
        enabled: true,
        latency: 428,
        qualityScore: 97,
        health: 'online',
      },
      {
        id: 'image-market',
        listingId: null,
        name: '',
        nameKey: 'showcase.routing.channels.imageMarket',
        provider: 'Canvas Relay',
        model: 'gpt-image-2',
        source: 'market',
        weight: 35,
        enabled: true,
        latency: 512,
        qualityScore: 93,
        health: 'online',
      },
    ],
  },
]
