// Stub for antd peer dependency required by @lobehub/icons
export const theme = { useToken: () => ({ token: {} }) };
export const Grid = { useBreakpoint: () => ({}) };
export const version = '5.0.0';
export const ConfigProvider = ({ children }) => children;
export const App = ({ children }) => children;
export const Image = () => null;
export const Skeleton = () => null;
export const Divider = () => null;
export const Select = () => null;
export const Input = () => null;
export const InputNumber = () => null;
export const Button = () => null;
export const Modal = () => null;
export const Drawer = () => null;
export const Dropdown = () => null;
export const Tooltip = () => null;
export const Tag = () => null;
export const Tabs = () => null;
export const Collapse = () => null;
export const Anchor = () => null;
export const Popover = () => null;
export const Upload = () => null;
export const message = { success: () => {}, error: () => {}, warning: () => {} };
export const notification = { success: () => {}, error: () => {} };
export const Form = Object.assign(() => null, { Item: () => null, useForm: () => [{}] });
export const Menu = () => null;
export const Avatar = () => null;
export const Alert = () => null;
export const Empty = () => null;
export const Segmented = () => null;
export const DatePicker = () => null;
export const ColorPicker = () => null;
export const AutoComplete = () => null;
export const Slider = () => null;
