package storage

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"os"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNewS3ArtifactStoreRequiresCredentials(t *testing.T) {
	t.Setenv("S3_BUCKET", "")
	t.Setenv("S3_ACCESS_KEY_ID", "")
	t.Setenv("S3_SECRET_ACCESS_KEY", "")
	_, err := NewS3ArtifactStore(context.Background())
	require.Error(t, err)
	assert.NotContains(t, err.Error(), "secret-value")
}

func TestValidateS3Endpoint(t *testing.T) {
	require.NoError(t, validateEndpoint("http://minio:9000"))
	require.Error(t, validateEndpoint("file:///tmp/bucket"))
	require.Error(t, validateEndpoint("https://user:pass@example.com"))
}

func TestS3ArtifactStoreIntegration(t *testing.T) {
	if os.Getenv("S3_INTEGRATION_TEST") != "1" {
		t.Skip("set S3_INTEGRATION_TEST=1 to run against an S3-compatible service")
	}
	store, err := NewS3ArtifactStore(context.Background())
	require.NoError(t, err)
	key := "integration/artifact-store-" + time.Now().UTC().Format("20060102T150405.000000000") + ".png"
	payload := []byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n', 0, 0, 0, 0}
	t.Cleanup(func() {
		require.NoError(t, store.Delete(context.Background(), key))
	})
	require.NoError(t, store.Put(context.Background(), key, bytes.NewReader(payload), "image/png"))
	signedURL, err := store.SignedURL(context.Background(), key, time.Minute)
	require.NoError(t, err)
	response, err := http.Get(signedURL) // #nosec G107 -- URL is generated by the configured test object store.
	require.NoError(t, err)
	defer response.Body.Close()
	assert.Equal(t, http.StatusOK, response.StatusCode)
	downloaded, err := io.ReadAll(response.Body)
	require.NoError(t, err)
	assert.Equal(t, payload, downloaded)
}
