
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/QuantumNous/new-api/relay/channel/gemini"


)

var tests = []testing.InternalTest{

	{"TestConvertOpenAIResponsesRequestToGeminiInstructionsAndInput", _test.TestConvertOpenAIResponsesRequestToGeminiInstructionsAndInput},

	{"TestConvertOpenAIResponsesRequestToGeminiFunctionToolAndChoice", _test.TestConvertOpenAIResponsesRequestToGeminiFunctionToolAndChoice},

	{"TestConvertOpenAIResponsesRequestToGeminiFunctionCallConversation", _test.TestConvertOpenAIResponsesRequestToGeminiFunctionCallConversation},

	{"TestConvertOpenAIResponsesRequestToGeminiKeepsCustomToolCalls", _test.TestConvertOpenAIResponsesRequestToGeminiKeepsCustomToolCalls},

	{"TestStreamResponseGeminiChat2OpenAIAttachesUsageMetadata", _test.TestStreamResponseGeminiChat2OpenAIAttachesUsageMetadata},

	{"TestGeminiChatStreamHandlerClaudeFirstFrameUsesUpstreamUsage", _test.TestGeminiChatStreamHandlerClaudeFirstFrameUsesUpstreamUsage},

	{"TestGeminiChatHandlerCompletionTokensExcludeToolUsePromptTokens", _test.TestGeminiChatHandlerCompletionTokensExcludeToolUsePromptTokens},

	{"TestGeminiStreamHandlerCompletionTokensExcludeToolUsePromptTokens", _test.TestGeminiStreamHandlerCompletionTokensExcludeToolUsePromptTokens},

	{"TestGeminiTextGenerationHandlerPromptTokensIncludeToolUsePromptTokens", _test.TestGeminiTextGenerationHandlerPromptTokensIncludeToolUsePromptTokens},

	{"TestGeminiChatHandlerUsesEstimatedPromptTokensWhenUsagePromptMissing", _test.TestGeminiChatHandlerUsesEstimatedPromptTokensWhenUsagePromptMissing},

	{"TestGeminiStreamHandlerUsesEstimatedPromptTokensWhenUsagePromptMissing", _test.TestGeminiStreamHandlerUsesEstimatedPromptTokensWhenUsagePromptMissing},

	{"TestGeminiTextGenerationHandlerUsesEstimatedPromptTokensWhenUsagePromptMissing", _test.TestGeminiTextGenerationHandlerUsesEstimatedPromptTokensWhenUsagePromptMissing},

	{"TestGeminiChatHandlerMissingUsageMetadataBuildsEstimatedBillingUsage", _test.TestGeminiChatHandlerMissingUsageMetadataBuildsEstimatedBillingUsage},

	{"TestGeminiStreamHandlerPromptOnlyUsageMetadataEstimatesCompletionTokens", _test.TestGeminiStreamHandlerPromptOnlyUsageMetadataEstimatesCompletionTokens},

	{"TestGeminiChatHandlerPromptOnlyUsageMetadataEstimatesCompletionTokens", _test.TestGeminiChatHandlerPromptOnlyUsageMetadataEstimatesCompletionTokens},

	{"TestGeminiStreamHandlerEmptyUsageMetadataBuildsEstimatedBillingUsage", _test.TestGeminiStreamHandlerEmptyUsageMetadataBuildsEstimatedBillingUsage},

	{"TestGeminiHandlersCountGroundingQueries", _test.TestGeminiHandlersCountGroundingQueries},

	{"TestGeminiResponsesHandlerReturnsOpenAIResponsesJSON", _test.TestGeminiResponsesHandlerReturnsOpenAIResponsesJSON},

	{"TestGeminiResponsesHandlerClosesBodyOnReadError", _test.TestGeminiResponsesHandlerClosesBodyOnReadError},

	{"TestGeminiResponsesStreamHandlerReturnsOpenAIResponsesSSE", _test.TestGeminiResponsesStreamHandlerReturnsOpenAIResponsesSSE},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/QuantumNous/new-api"
	testdeps.ImportPath = "github.com/QuantumNous/new-api/relay/channel/gemini"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

